= Dockerfile for lra-coordinator

The Dockerfile in this folder builds an image for the LRA coordinator, which can be used to manage Long Running Actions (more info [here](https://www.narayana.io//docs/project/index.html#d0e15502))

== Environment Variables

The following environment variables can be used when building the image.

* `NARAYANA_VERSION` is used only during the `build` phase and defines what version of Narayana's LRA coordinator  will be downloaded
* `NARAYANA_FULL_URL` is used during the `build` phase to set up the location where the Narayana distro will be downloaded from
* `LOG_LEVEL` is used during the `run` phase to set up the level/accuracy of logging produced by the LRA coordinator. The permitted values are logging levels defined in the [Quarkus runtime](https://quarkus.io/guides/logging). The default logging level value is `INFO`.
* `OBJECT_STORE_PATH` is used during the `run` phase to set up a directory where the transaction log is stored (which is the persistent storage of the LRA coordinator). The default location is the directory `/data`.

The lra coordinator is run by the user `jboss` and exposes port `8080` for communication.

== Build

```bash
export NARAYANA_VERSION=...
podman build --tag lra-coordinator --build-arg NARAYANA_VERSION=${NARAYANA_VERSION}
```

== Running the image locally

The following command runs `lra-cordinator` locally and sets up the logging level to `TRACE`.

```bash
podman run -p 8080:8080 --rm -it -e LOG_LEVEL=TRACE lra-coordinator
```

== Image Repository

The image of `lra-coordinator` is available in Narayana's official [quay.io repository](https://quay.io/repository/jbosstm/lra-coordinator):

```bash
podman pull quay.io/jbosstm/lra-coordinator:latest
```

== Release the lra docker image

After building the image of `lra-coordinator` (as explained in the section `Build`), it is possible to tag and push the new version to `quay.io` following the commands:

```bash
# tagging the lra-coordinator to push it
podman tag lra-coordinator quay.io/jbosstm/lra-coordinator:${NARAYANA_VERSION}
podman tag lra-coordinator quay.io/jbosstm/lra-coordinator:latest
# logging to quay.io
podman login quay.io
# pushing the tagged image
podman push quay.io/jbosstm/lra-coordinator:${NARAYANA_VERSION}
podman push quay.io/jbosstm/lra-coordinator:latest
```

== Running the lra-coordinator image in OpenShift

This docker image is used also to start the `lra-coordinator` in OpenShift. Please, refer to the link:../openshift-template[template] in this repo.
